### ISSUE TITLE
New to this. Some assistance would be nice.

### ISSUE THREAD

**Issue by jakenegroni** [yousefissa/SplashSource#3]
I really appreciate what your doing for the community and hopefully this will help me cop a couple of Yeezys. I have everything downloaded and was wondering what or how to get Python 3+ is and also what system these things will run on (Python 3+?) Thanks. Not sure if you can private message on here but my email is Jacob.negroni@yahoo.com

**Comment by Eldogfart** [comment]
You're already way behind chief. All of those things can be googled/youtubed. If you can't do that, then find another hobby.

**Comment by jakenegroni** [comment]
Not actually... This is something I like to do and I will keep doing it. I use to try my luck and wait in the queue but I am tired of taking L's and now I want to learn about the technology and coding behind it and how to cop.
